# -*- coding: utf-8 -*-
"""ocean_plastic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHaDaOIRFC8qHvMQDQMReZDui_B58kpP
"""

!pip install ultralytics -q
!pip install kagglehub -q
!pip install opencv-python matplotlib -q

import os
import cv2
import yaml
import glob
import random
import shutil
import matplotlib.pyplot as plt
from ultralytics import YOLO

import kagglehub

path = kagglehub.dataset_download("mexwell/trashcan-1-0")

print("Dataset downloaded at:")
print(path)

for root, dirs, files in os.walk(path):
    print("ROOT:", root)
    print("DIRS:", dirs[:5])
    print("FILES:", files[:5])
    print("-"*50)

images = glob.glob(path + "/**/*.jpg", recursive=True)

print("Total images found:", len(images))

sample_images = random.sample(images, 5)

plt.figure(figsize=(15,10))

for i, img_path in enumerate(sample_images):

    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.subplot(2,3,i+1)
    plt.imshow(img)
    plt.title(os.path.basename(img_path))
    plt.axis("off")

plt.tight_layout()
plt.show()

!pip install pycocotools -q

import json
from tqdm import tqdm

TRAIN_JSON = "/root/.cache/kagglehub/datasets/mexwell/trashcan-1-0/versions/1/dataset/material_version/instances_train_trashcan.json"

VAL_JSON = "/root/.cache/kagglehub/datasets/mexwell/trashcan-1-0/versions/1/dataset/material_version/instances_val_trashcan.json"

TRAIN_IMAGES = "/root/.cache/kagglehub/datasets/mexwell/trashcan-1-0/versions/1/dataset/material_version/train"

VAL_IMAGES = "/root/.cache/kagglehub/datasets/mexwell/trashcan-1-0/versions/1/dataset/material_version/val"

BASE_DIR = "/content/yolo_dataset"

folders = [
    "images/train",
    "images/val",
    "labels/train",
    "labels/val"
]

for folder in folders:
    os.makedirs(os.path.join(BASE_DIR, folder), exist_ok=True)

print("YOLO folders created.")

def convert_coco_to_yolo(json_path, images_folder, output_labels_dir, output_images_dir):

    with open(json_path) as f:
        coco = json.load(f)

    images = coco['images']
    annotations = coco['annotations']

    image_id_to_annotations = {}

    for ann in annotations:

        image_id = ann['image_id']

        if image_id not in image_id_to_annotations:
            image_id_to_annotations[image_id] = []

        image_id_to_annotations[image_id].append(ann)

    for image in tqdm(images):

        image_id = image['id']
        image_filename = image['file_name']

        src_image_path = os.path.join(images_folder, image_filename)

        if not os.path.exists(src_image_path):
            continue

        dst_image_path = os.path.join(output_images_dir, image_filename)

        shutil.copy(src_image_path, dst_image_path)

        label_filename = image_filename.replace(".jpg", ".txt")

        label_path = os.path.join(output_labels_dir, label_filename)

        img_w = image['width']
        img_h = image['height']

        lines = []

        if image_id in image_id_to_annotations:

            for ann in image_id_to_annotations[image_id]:

                bbox = ann['bbox']

                x, y, w, h = bbox

                x_center = (x + w/2) / img_w
                y_center = (y + h/2) / img_h

                w = w / img_w
                h = h / img_h

                # EVERYTHING = ONE CLASS (plastic)
                class_id = 0

                line = f"{class_id} {x_center} {y_center} {w} {h}"

                lines.append(line)

        with open(label_path, "w") as f:
            f.write("\n".join(lines))

convert_coco_to_yolo(
    json_path=TRAIN_JSON,
    images_folder=TRAIN_IMAGES,
    output_labels_dir="/content/yolo_dataset/labels/train",
    output_images_dir="/content/yolo_dataset/images/train"
)

convert_coco_to_yolo(
    json_path=VAL_JSON,
    images_folder=VAL_IMAGES,
    output_labels_dir="/content/yolo_dataset/labels/val",
    output_images_dir="/content/yolo_dataset/images/val"
)

data_yaml = """
path: /content/yolo_dataset

train: images/train
val: images/val

names:
  0: plastic
"""

with open("/content/yolo_dataset/data.yaml", "w") as f:
    f.write(data_yaml)

print("data.yaml created.")

print("Train images:",
      len(os.listdir("/content/yolo_dataset/images/train")))

print("Train labels:",
      len(os.listdir("/content/yolo_dataset/labels/train")))

print("Val images:",
      len(os.listdir("/content/yolo_dataset/images/val")))

print("Val labels:",
      len(os.listdir("/content/yolo_dataset/labels/val")))

model = YOLO("yolov8m.pt")

model.train(

    data="/content/yolo_dataset/data.yaml",

    epochs=20,

    imgsz=640,

    batch=16,

    device=0,

    workers=2,
    patience=3,

    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,

    degrees=10,
    translate=0.1,
    scale=0.5,

    fliplr=0.5,

    mosaic=1.0
)

import glob

val_images = glob.glob(
    "/content/yolo_dataset/images/val/*.jpg"
)

print("Validation images found:", len(val_images))

import random

# Pick 5 random validation images
random_images = random.sample(val_images, 5)

# Run predictions
results = model.predict(

    source=random_images,

    conf=0.15,

    save=True
)

from IPython.display import display, Image
import glob
import os

# Find latest predict folder
latest_predict_folder = sorted(
    glob.glob("runs/detect/predict*"),
    key=os.path.getmtime
)[-1]

print("Using folder:", latest_predict_folder)

# Get all predicted images
predicted_images = glob.glob(latest_predict_folder + "/*.jpg")

print("Images found:", len(predicted_images))

# Display images
for img in predicted_images:
    display(Image(filename=img))

from google.colab import files
from IPython.display import display, Image
import glob
import os

uploaded = files.upload()

uploaded_filename = list(uploaded.keys())[0]

print("Uploaded:", uploaded_filename)

results = model.predict(

    source=uploaded_filename,

    conf=0.15,

    save=True
)

latest_predict_folder = sorted(
    glob.glob("/content/runs/detect/predict*"),
    key=os.path.getmtime
)[-1]

print("Using folder:", latest_predict_folder)

predicted_images = sorted(
    glob.glob(latest_predict_folder + "/*"),
    key=os.path.getmtime
)

latest_image = predicted_images[-1]

print("Displaying:", latest_image)

display(Image(filename=latest_image))

from google.colab import files

files.download("/content/runs/detect/train-2/weights/best.pt")